FROM confluent/platform:3.0.0
MAINTAINER Jonathon W. Marshall <jmarshall@bigvikinggames.com>

RUN wget -q http://central.maven.org/maven2/mysql/mysql-connector-java/5.1.39/mysql-connector-java-5.1.39.jar -O /usr/share/java/kafka-connect-jdbc/mysql-connector-java-5.1.39.jar
